# -----------------------------------------------------------
#                          Testing ci/cd
#
#                  Copyleft (c) HennessyFamq
#
# -----------------------------------------------------------
name: full_ci-cd_latest 
env:
  Plasik_APPLICATION_NAME: "MyPlasik"
  Plasik_ENVIRONMENT: "MyPlasik-env"
  Plasik_DEPLOY_PACKAGE_NAME: "plasik_app_${{github.sha}}.zip"

on: 
  push:
    branches: [main,feature-new]
  pull_request:
    branches: [main]

jobs:
  ci_part:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone git-repo
      uses: actions/chechout@v4
    - name: Create ZIP deployment package
      run: zip -r ${{env.Plasik_DEPLOY_PACKAGE_NAME}} ./ -x *.git*
