# -----------------------------------------------------------
#                          Testing ci
#
#                  Copyleft (c) HennessyFamq
#
# -----------------------------------------------------------
name: CIplasikTest
env:
  APPLICATION_NAME    : "MyPlasik"
  DEPLOY_PACKAGE_NAME : "plasik_deploy-ver-${{ github.sha }}"
  
  

on: 
  push:
    branches:
    - main

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name:
        uses: actions/checkout@v1
      
      - name: printing helloword from tst
        run: echo "helloword from testing job"
        
      - name: execure few commands
        run: |
          echo "Hello msg1"
          echo "hello msg2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
      - name: list current folder
        run: ls -la
      - name: switching dir
        run: cd CI-CD
      - name: main commands
        run: |
          ls -la
          cat bot_code.ph
          cd /logs
          :> log.top
          top >> log.top
      
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: printing helloword from dpl
        run: echo "helloword from deploy job"
        
      - name: Deoployment package
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
    needs: Testing
